
#pragma once

typedef enum
{
	DOCKPANEL_VIDEO,
	DOCKPANEL_VIDEOEX,
	DOCKPANEL_STAGECTL,
	DOCKPANEL_DMDCTL,
	DOCKPANEL_SCANERDLG,
	DOCKPANEL_MAPVIEWDLG,
	DOCKPANEL_DIFF,
	DOCKPANEL_DCAMCTL,
}DOCKPANEL_TYPE;

typedef enum
{
	VIEWPANEL_REALTIME,
	VIEWPANEL_CONFOCAL,
	VIEWPANEL_REALTIMEEX,
	VIEWPANEL_CONFOCALEX,
	//VIEWPANEL_3D,
	VIEWPANEL_3DRange,
	VIEWPANEL_COLOR,
	VIEWPANEL_ViewFocus,
	VIEWPANEL_SI,
	VIEWPANEL_DIFF_MEASURE_VIEW,
	VIEWPANEL_3D,
}VIEWPANEL_TYPE;

typedef enum
{
	MSG_TIME,
	MSG_CALCV
}MESSAGE_TYPE;